version: '2.1'

services:
  sensor-monitor:
    build: ./sensor-monitor
    privileged: true
    restart: unless-stopped
    network_mode: host
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/mem:/dev/mem"
    environment:
      - MQTT_BROKER=broker.hivemq.com
      - MQTT_PORT=1883
      - MQTT_TOPIC=balena/gpio/sensor
      - SENSOR_INTERVAL=5
      - GPIO_PIN=14
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
