FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3.11-build

WORKDIR /usr/src/app

RUN install_packages \
    build-essential \
    python3-dev \
    python3-pip

COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt

COPY . ./

CMD ["python3", "main.py"]
